version: 2.1

orbs:
  ruby: circleci/ruby@1.6.0
  node: circleci/node@5.0.2

jobs:
  build_back:
    docker:
      - image: cimg/ruby:3.1.1-node-browser
      environment:
        - BUNDLER_VERSION: 2.3.7
        - RAILS_ENV: 'test'
    working_directory: ~/repo
    steps:
      - checkout:
          path: back
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
  test_back:
    docker:
       - image: cimg/ruby:3.1.1-node-browse
       - image: cimg/postgres:14.1.0
         environment:
           POSTGRES_PASSWORD: circleci-demo-ruby
           POSTGRES_DATABASE: rails_blog_test
           POSTGRES_USER: ""
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      PGUSER: circleci-demo-ruby
      PGPASSWORD: ""
      RAILS_ENV: test
    working_directory: ~/repo/back
    steps:
      - checkout:
        path: ~/spa/back
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
        name: Database_setup
        command: bundle exec rails db:schema:load --trace
      - ruby/rspec-test
      #- ruby/rubocop-check 
      working_directory: ~/repo/back

  build_front:
    docker:
      -image: cimg/node:16.14.0
    working_directory: ~/repo
    step:
      - checkout
      - restore_cache:
          name: restore Yarn cache
          keys:
            - yarn-packages-{{ checksum "spa/front/yarn.lock" }}
      - run:
          name: install dependencies
          command: yarn install --frozen-lockfile
          working_directory: ~/spa/front
      - save_cache:
          name: keep Yarn package cache
          key: yarn-packages-{{ checksum "spa/front/yarn.lock" }}
          paths:
            - front/.cache/yarn
      - run: 
          name: build front
          command: yarn run dev
          working_directory: ~/spa/front
      - persist_to_workspace:
          root: .
          paths:
            - ~/spa/front
  test_front:
    docker:
      - image: cimg/node:16.14.0
    working_directory: ~/spa/front
    steps:
      - attach_workspace:
          at: .
      - run: 
          name: jest test 
          command: yarn test
          working_directory: ~/spa/front
      - persist_to_workspace:
          root: .
          paths:
            - ~/spa/front

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_back
      - test_back:
          filters:
            branches:
              ignore: main
      - build_front
      - test_front:
          filters:
            branches:
              ignore: main