version: 2

jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
        name: create .env
        command: |
          touch .env
          WORKDIR=${WORKDIR} > .env
          CONTAINER_PORT=${CONTAINER_PORT} >> .env
          API_PORT=${API_PORT} >> .env
          FRONT_PORT=${FRONT_PORT} >> .env
          POSTGRES_PASSWORD=${POSTGRES_PASSWORD} >> .env
      - run:
        name: docker-compose up
        command: docker-compose up -d
      - run:
        name: docker ps -a
        command: docker ps -a
      - run:
        name: rails_db_migrate
        command: docker exec -it spa-back-1 rails db:migrate
      - run:
        name: rails_test_rspec
        command: docker exec -it spa-back-1 rspec
      - run:
        name: nuxt_test_jest
        command: docker exec -it spa-front-1 yarn test
      - run:
        name: docker-compose down
        command: docker-compose down
      

workflows:
  version: 2
  build_and_test:
    jobs:
      - build