source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.7.6"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
# Ruby 2.7.0以上が必須、Ruby 3.0以上が望ましい
gem "rails", "~> 6.1.6"

# Use postgresql as the database for Active Record
gem "pg", "~> 1.3.4"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.6.2"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
gem "bcrypt", "~> 3.1.17"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
#Bootsnapのバージョンは1.4.2以上にする必要があります
gem "bootsnap", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem "rack-cors"

# Use device gem and device_token_auth gem to implement token authentication function
gem 'devise', '~> 4.8.1'
gem 'devise_token_auth', '>= 1.2.0', git: "https://github.com/lynndylanhurley/devise_token_auth"

gem 'webpacker'

gem 'pry-rails'

gem 'jquery-rails'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem 'factory_bot_rails'
  gem 'rspec-rails'
end

group :development do
  gem 'pry-byebug'
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
  #アプリケーションでspring gemを使っている場合は、spring gemのバージョンを3.0.0以上にアップグレードする必要があります。そうしないと以下のエラーが発生します
  #undefined method `mechanism=' for ActiveSupport::Dependencies:Module
  #config/environments/test.rbでconfig.cache_classes設定を必ずfalseにしてください
end